language: node_js
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
services:
  - docker
node_js:
  - 11
before_install:
  - npm install -g gulp yarn
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/framework.git unitejs/unitejs-framework
  - cd unitejs/unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/cli-core.git unitejs/unitejs-cli-core
  - cd unitejs/unitejs-cli-core
  - npm link unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/packages.git unitejs/unitejs-packages
  - cd unitejs/unitejs-packages
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/engine.git unitejs/unitejs-engine
  - cd unitejs/unitejs-engine
  - npm link unitejs-framework unitejs-packages
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/image.git unitejs/unitejs-image
  - cd unitejs/unitejs-image
  - npm link unitejs-framework
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/image-cli.git unitejs/unitejs-image-cli
  - cd unitejs/unitejs-image-cli
  - npm link unitejs-framework unitejs-cli-core unitejs-image
  - npm link
  - yarn link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/unitejs/cli.git unitejs/unitejs-cli
  - cd unitejs/unitejs-cli
  - npm link unitejs-framework unitejs-cli-core unitejs-engine
  - cd ../../
script: 
  - chmod +x ./build.sh
  - chmod +x ./create-apps.sh
  - ./build.sh || travis_terminate 1
